const DATA = [
["Fortnite","Battle Royale","V-Bucks, Accounts",280,"V-Bucks","https://cdn2.unrealengine.com/en-fn-og-42-10-c1sx-egs-launcher-blade-2560x1440-2560x1440-319ff81b274e.jpg"],
["PUBG Mobile","Battle Royale","UC, Accounts",220,"UC","https://www.independentarabia.com/sites/default/files/thumbnails/image/2020/06/07/208186-2056759375.jpg"],
["Call of Duty","Battle Royale","CP, Accounts",450,"CP","https://vigiato.net/wp-content/uploads/2023/08/modern-warfare-3-mw2-dlc.jpg"],
["Apex Legends","Battle Royale","Apex Coins, Accounts",450,"Apex Coins","https://cdn.cloudflare.steamstatic.com/steam/apps/1172470/header.jpg"],
["Free Fire","Battle Royale","Diamonds, Accounts",180,"Diamonds","https://telegrafi.com/media-library/2022-02-garena-free-fire-jpg.jpg?coordinates=150%2C0%2C150%2C0&height=1500&id=57961205&width=2000"],
["Valorant","Tactical","VP, Accounts",350,"VP","https://cmsassets.rgpub.io/sanity/images/dsfx7636/news_live/8f0df8efd5b986039cd37a4d5f3bf31b815d0c54-3840x2160.jpg"],
["League of Legends","Tactical","RP, Accounts",300,"RP","https://ruined.dev/_next/image?q=75&url=https%3A%2F%2Fruined.dev%2Fwp-content%2Fuploads%2F2021%2F05%2Fteam_graves_2-rcm1024x0u.jpg&w=1200"],
["Clash Royale","Tactical","Gems, Accounts",150,"Gems","https://cdn.mobygames.com/promos/2601358-clash-royale-other.jpg"],
["Brawl Stars","Tactical","Gems, Accounts",180,"Gems","https://www.klicksafe.eu/fileadmin/_processed_/9/9/csm_Sharepic_Brawl-Stars_905ff3013c.png"],
["Genshin Impact","RPG & Open World","Primogems, Accounts",280,"Primogems","https://www.teyvatavern.com/cdn/shop/collections/genshin-impact-official-merch-945659.jpg?v=1739288877"],
["Wuthering Waves","RPG & Open World","Astrite, Accounts",300,"Astrite","https://cdn1.epicgames.com/spt-assets/c1586295960b46f88bbfeec32c199e0e/wuthering-waves-uw6vy.jpg"],
["Neverness to Everness","RPG & Open World","Currency, Accounts",300,"Currency","https://cdn1.epicgames.com/spt-assets/fb7cc56133de4df99b6a95d0a6b35d56/nte-neverness-to-everness-sqyfp.jpg"],
["GTA V Online","RPG & Open World","Cash Boosts, Accounts",500,"Cash Boost","https://p2.bahamut.com.tw/B/2KU/64/911515c004fa2a8d72009cee861fl845.JPG?v=1647400010929"],
["Minecraft","Sandbox","Premium Java/Bedrock",1800,"Premium Account","https://ethlan.fr/img/jeux/121.jpg"],
["Roblox","Sandbox","Robux, Accounts",200,"Robux","https://store-images.s-microsoft.com/image/apps.47252.13510798883386282.a1e5df65-8dd7-427c-9da9-506afa37b254.f4132380-deee-4518-8bbd-2a9b540046f3"],
["Discord Nitro","Media & Utility","Subscriptions",450,"Nitro","https://img.tamindir.com/2023/11/253503/discord-nitro.jpg"],
["Crunchyroll","Media & Utility","Premium",600,"Premium","https://i.blogs.es/2c137a/sin-titulo-2/840_560.jpeg"],
["Marvel Rivals","Media & Utility","Units, Accounts",350,"Units","https://www.amd.com/content/dam/amd/en/images/games/marvel-rivals/3032700-marvel-rivals-screen-blk.jpg"]
];
const PACKAGES={
"Fortnite":[["1,000 V-Bucks",280],["2,800 V-Bucks",720],["5,000 V-Bucks",1250],["13,500 V-Bucks",3000]],"PUBG Mobile":[["325 UC",220],["660 UC",430],["1,800 UC",1050],["3,850 UC",2100]],"Call of Duty":[["420 CP",450],["880 CP",850],["2,400 CP",2200],["5,000 CP",4200]],"Apex Legends":[["600 Coins",450],["1,000 Coins",700],["2,150 Coins",1400]],"Free Fire":[["100 Diamonds",180],["310 Diamonds",450],["520 Diamonds",720],["1,060 Diamonds",1350]],"Valorant":[["475 VP",350],["1,000 VP",700],["2,050 VP",1350],["5,350 VP",3300]],"League of Legends":[["575 RP",300],["1,380 RP",700],["2,800 RP",1350],["6,500 RP",3000]],"Clash Royale":[["500 Gems",150],["1,200 Gems",320],["2,500 Gems",650],["5,500 Gems",1300]],"Brawl Stars":[["170 Gems",180],["360 Gems",350],["950 Gems",850]],"Genshin Impact":[["60 Primogems",280],["300 + 30 Bonus",1100],["980 + 110 Bonus",2800],["1980 + 260 Bonus",5400],["3280 + 600 Bonus",8500],["6480 + 1600 Bonus",16000]],"Wuthering Waves":[["300 Astrite",300],["980 Astrite",850],["Endgame Account",1800]],"Neverness to Everness":[["Starter Pack",300],["Currency Pack",800],["Early Account",1800]],"GTA V Online":[["$1M Boost",500],["$5M Boost",1200],["$10M Boost",2200]],"Minecraft":[["Java Account",1800],["Bedrock Account",1800],["Java + Bedrock",2400]],"Roblox":[["400 Robux",200],["800 Robux",380],["1,700 Robux",760],["4,500 Robux",1900]],"Discord Nitro":[["1 Month Nitro",450],["3 Months Nitro",1200],["1 Year Nitro",4200]],"Crunchyroll":[["1 Month Premium",600],["3 Months Premium",1600],["1 Year Premium",5000]],"Marvel Rivals":[["500 Units",350],["1,000 Units",650],["Early Account",1500]]};
const fmt=n=>`PKR ${Number(n).toLocaleString()}`;
const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function setupMenu(){const b=document.querySelector('.menu'),n=document.querySelector('.navlinks');if(b&&n)b.onclick=()=>n.classList.toggle('open')}
function gameCard(p){return `<a class="game-card" href="checkout.html?game=${encodeURIComponent(p[0])}"><div class="game-img"><span class="game-badge">${esc(p[1])}</span><img src="${p[5]}" alt="${esc(p[0])}" loading="lazy"></div><div class="game-info"><h3>${esc(p[0])}</h3><p>${esc(p[2])}</p><div class="game-meta"><span class="from">From<b>${fmt(p[3])}</b></span><span class="mini-cart">⌑</span></div></div></a>`}
function renderGrid(el,filter='',query=''){let arr=DATA.filter(p=>(!filter||filter==='All Games'||p[1]===filter)&&(!query||p.join(' ').toLowerCase().includes(query.toLowerCase())));if(el.dataset.limit)arr=arr.slice(0,+el.dataset.limit);el.innerHTML=arr.length?arr.map(gameCard).join(''):'<div class="empty">No games match your search.</div>'}
function initCatalog(){const grid=document.querySelector('#gameGrid');if(!grid)return;const input=document.querySelector('#catalogSearch');if(input){const q=new URLSearchParams(location.search).get('q');if(q)input.value=q}let filter=new URLSearchParams(location.search).get('category')||'All Games';const filters=[...document.querySelectorAll('.filter')];filters.forEach(b=>b.classList.toggle('active',b.dataset.filter===filter));const draw=()=>renderGrid(grid,filter,input?.value||'');filters.forEach(b=>b.onclick=()=>{filter=b.dataset.filter;filters.forEach(x=>x.classList.toggle('active',x===b));draw()});input?.addEventListener('input',draw);draw()}
function initHome(){const track=document.querySelector('#carouselTrack');if(!track)return;const picks=['Fortnite','Valorant','Genshin Impact','GTA V Online','PUBG Mobile','Call of Duty','Free Fire','Roblox'];const slides=picks.map(n=>DATA.find(p=>p[0]===n));track.innerHTML=slides.map((p,i)=>`<a class="slide" href="checkout.html?game=${encodeURIComponent(p[0])}" data-i="${i}"><img src="${p[5]}" alt="${esc(p[0])}"></a>`).join('');const dots=document.querySelector('#dots');dots.innerHTML=slides.map((_,i)=>`<button aria-label="Show slide ${i+1}"></button>`).join('');let center=0;function paint(){document.querySelectorAll('.slide').forEach((s,i)=>{let d=(i-center+slides.length)%slides.length;if(d>4)d-=slides.length;const pos={[-4]:'s0',[-3]:'s1',[-2]:'s2',[-1]:'s3',[0]:'s4',[1]:'s5',[2]:'s6',[3]:'s7'}[d]||'s0';s.className='slide '+pos;});[...dots.children].forEach((d,i)=>d.classList.toggle('active',i===center));}function next(){center=(center+1)%slides.length;paint()}function prev(){center=(center-1+slides.length)%slides.length;paint()}document.querySelector('.carousel-arrow.right').onclick=next;document.querySelector('.carousel-arrow.left').onclick=prev;[...dots.children].forEach((d,i)=>d.onclick=()=>{center=i;paint()});paint();let timer=setInterval(next,3600);track.parentElement.onmouseenter=()=>clearInterval(timer);track.parentElement.onmouseleave=()=>timer=setInterval(next,3600)}
function currentGame(){const q=new URLSearchParams(location.search).get('game');return DATA.find(x=>x[0].toLowerCase()===String(q||'').toLowerCase())||DATA[0]}
function initCheckout(){const root=document.querySelector('#checkout');if(!root)return;const p=currentGame();let type='currency',pack=PACKAGES[p[0]][0];const accountPackages=[[`Verified ${p[0]} Account`,p[3]*4],[`Premium ${p[0]} Account`,p[3]*7],[`Endgame ${p[0]} Account`,p[3]*10]];document.querySelector('#summaryArt').src=p[5];document.querySelector('#summaryName').textContent=p[0];document.querySelector('#summaryMeta').textContent=p[2];const list=document.querySelector('#packageList');function options(){return type==='currency'?PACKAGES[p[0]]:accountPackages}function draw(){list.innerHTML=options().map((x,i)=>`<button class="package-btn ${x[0]===pack[0]?'active':''}" data-i="${i}"><span>${esc(x[0])}</span><b>${fmt(x[1])}</b></button>`).join('');list.querySelectorAll('.package-btn').forEach(b=>b.onclick=()=>{pack=options()[+b.dataset.i];draw();receipt()})}function receipt(){document.querySelector('#receipt').innerHTML=`<div class="receipt-title">ORDER SUMMARY</div><div class="receipt-row"><span>Product</span><b>${esc(p[0])}</b></div><div class="receipt-row"><span>Package</span><b>${esc(pack[0])}</b></div><div class="receipt-row"><span>Type</span><b>${type==='currency'?'In-game currency':'Account'}</b></div><div class="receipt-row receipt-total"><span>Total</span><b>${fmt(pack[1])}</b></div><div class="payment-box"><h3>SadaPay</h3><p>Payment details are shown here only because you are checking out.</p><div class="payment-number">03091847477</div><div class="payment-name">Kashif Ahmad Khan</div></div><button class="wa" id="sendWA">SEND ORDER ON WHATSAPP</button><button class="download" id="downloadReceipt">DOWNLOAD RECEIPT</button>`;document.querySelector('#sendWA').onclick=()=>{const msg=`Hello infixone.pk, I want to order%0A%0AGame: ${encodeURIComponent(p[0])}%0APackage: ${encodeURIComponent(pack[0])}%0AType: ${encodeURIComponent(type==='currency'?'In-game currency':'Account')}%0ATotal: ${encodeURIComponent(fmt(pack[1]))}`;window.open(`https://wa.me/923350453387?text=${msg}`,'_blank')};document.querySelector('#downloadReceipt').onclick=()=>{const txt=`infixone.pk ORDER\n\nGame: ${p[0]}\nPackage: ${pack[0]}\nType: ${type==='currency'?'In-game currency':'Account'}\nTotal: ${fmt(pack[1])}\nPayment: SadaPay 03091847477\nAccount Name: Kashif Ahmad Khan`;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([txt],{type:'text/plain'}));a.download='infixone-order.txt';a.click()}}document.querySelectorAll('.type-btn').forEach(b=>b.onclick=()=>{type=b.dataset.type;document.querySelectorAll('.type-btn').forEach(x=>x.classList.toggle('active',x===b));pack=options()[0];draw();receipt()});document.querySelector('#proceed').onclick=()=>{document.querySelector('.loader-screen')?.classList.add('show');setTimeout(()=>document.querySelector('.loader-screen')?.classList.remove('show'),650)};draw();receipt()}
setupMenu();initHome();initCatalog();initCheckout();const hs=document.querySelector('#homeSearch');if(hs)hs.addEventListener('keydown',e=>{if(e.key==='Enter'&&hs.value.trim())location.href='shop.html?q='+encodeURIComponent(hs.value.trim())});
